# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PlgMY9e-HovyR1wMv6ORMPCi1-GeUay
"""

position_1 = input().split()
position_2 = input().split()
x1 = int(position_1[0])
y1 = int(position_1[1])
x2 = int(position_2[0])
y2 = int(position_2[1])
dx = abs(x2 - x1)
dy = abs(y2 - y1)

if (((x1 == x2) and (y1 == y2)) or ((checkerboard[x2][y2] == 1))):
  print("No")
elif (dx >= 2 or dy >= 2):
  print("No")
else:
  print("Yes")