# -*- coding: utf-8 -*-
"""P1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QCl7iDMsFZf-YVm_RVKmqYVaPGGubt1
"""

position_1 = input().split()
position_2 = input().split()
x1 = int(position_1[0])
y1 = int(position_1[1])
x2 = int(position_2[0])
y2 = int(position_2[1])
dx = abs(x2 - x1)
dy = abs(y2 - y1)

if (((x1 == x2) and (y1 == y2)) or (checkerboard[x2][y2] == 1)):
  print("No")
elif ((dx != dy and (dx != 0 and dy != 0))):
  print("No")
else:
  step_x = (x2 - x1) // max(1, dx)
  step_y = (y2 - y1) // max(1, dy)

  cx = x1 + step_x
  cy = y1 + step_y
  reachable = True

  while (cx != x2) or (cy != y2):
    if checkerboard[cx][cy] == 1:
      reachable = False
      break
    cx += step_x
    cy += step_y

  if reachable == True:
    print("Yes")
  else:
    print("No")