# -*- coding: utf-8 -*-
"""P1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZqIFUv48tzxmZgcZPuyEKkDA84-Khb_
"""

position_1 = input().split()
position_2 = input().split()
x1 = int(position_1[0])
y1 = int(position_1[1])
x2 = int(position_2[0])
y2 = int(position_2[1])

if (((x1 == x2) and (y1 == y2)) or ((checkerboard[x2][y2] == 1))):
  print("No")
elif ((x2 - x1) == 1):
  print("Yes")
else:
  print("No")